var body = $response.body;
var obj = JSON.parse(body);

obj["subscription"] = {
    "state" : "PAYING",
    "tierName" : "",
    "catalog" : "105",
    "trialLengthDays" : 0,
    "billingPartnerCode" : "Rhapsody",
    "createDate" : "2022-06-11T10:28:56.000Z",
    "productName" : "Napster Plus",
    "isSuspended" : false,
    "tierCode" : "NAPSTER-PLUS",
    "productCode" : "Napster Plus",
    "isTrial" : false,
    "entitlements" : {
      "canStreamDocumentaryVideo" : true,
      "canStreamOnWeb" : true,
      "canStreamHiRes" : true,
      "canStreamInterviewVideo" : true,
      "canStreamConcertVideo" : true,
      "playBasedTierPeriod" : "monthly",
      "maxBitDepth" : 24,
      "canPlayPremiumRadio" : true,
      "canStreamSpecialEventVideo" : true,
      "canStreamWebisodeVideo" : true,
      "canStreamContentProviderOriginalsVideo" : true,
      "canStreamOnMobile" : true,
      "maxStreamCount" : 1,
      "hasStreamEntitlements" : true,
      "canStreamRawFootageVideo" : true,
      "canStreamTvShow" : true,
      "canStreamFeatureVideo" : true,
      "canStreamVrVideo" : true,
      "maxSampleRate" : 192000,
      "canStreamMusicVideo" : true,
      "maxStreamBitrate" : 192000,
      "canStreamMarketingVideo" : true,
      "canStreamAcousticVideo" : true,
      "canStreamOnPC" : true,
      "canStreamBehindTheScenesVideo" : true,
      "canStreamTrailerVideo" : true,
      "canStreamNapsterExclusiveVideo" : true,
      "canStream360Video" : true,
      "maxDownloadBitrate" : 192000,
      "canStreamOnHomeDevice" : true,
      "canStreamOnDemand" : true,
      "maxPcCount" : 3,
      "canUpgradeStreams" : true,
      "canStreamOffline" : true,
      "canStreamRadio" : true,
      "canStreamMakingOfVideo" : true,
      "isPlayBasedTier" : false,
      "maxDeviceCount" : 3
    },


body = JSON.stringify(obj);
$done({body});
